# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: asr.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='asr.proto',
  package='asr',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\tasr.proto\x12\x03\x61sr\"\x1f\n\nASRRequest\x12\x11\n\tutterance\x18\x01 \x01(\x0c\"$\n\x0b\x41SRResponse\x12\x15\n\rtranscription\x18\x01 \x01(\t2O\n\x13speechRecognization\x12\x38\n\x0fspeechRecognize\x12\x0f.asr.ASRRequest\x1a\x10.asr.ASRResponse\"\x00(\x01\x62\x06proto3'
)




_ASRREQUEST = _descriptor.Descriptor(
  name='ASRRequest',
  full_name='asr.ASRRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='utterance', full_name='asr.ASRRequest.utterance', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=18,
  serialized_end=49,
)


_ASRRESPONSE = _descriptor.Descriptor(
  name='ASRResponse',
  full_name='asr.ASRResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='transcription', full_name='asr.ASRResponse.transcription', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=51,
  serialized_end=87,
)

DESCRIPTOR.message_types_by_name['ASRRequest'] = _ASRREQUEST
DESCRIPTOR.message_types_by_name['ASRResponse'] = _ASRRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ASRRequest = _reflection.GeneratedProtocolMessageType('ASRRequest', (_message.Message,), {
  'DESCRIPTOR' : _ASRREQUEST,
  '__module__' : 'asr_pb2'
  # @@protoc_insertion_point(class_scope:asr.ASRRequest)
  })
_sym_db.RegisterMessage(ASRRequest)

ASRResponse = _reflection.GeneratedProtocolMessageType('ASRResponse', (_message.Message,), {
  'DESCRIPTOR' : _ASRRESPONSE,
  '__module__' : 'asr_pb2'
  # @@protoc_insertion_point(class_scope:asr.ASRResponse)
  })
_sym_db.RegisterMessage(ASRResponse)



_SPEECHRECOGNIZATION = _descriptor.ServiceDescriptor(
  name='speechRecognization',
  full_name='asr.speechRecognization',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=89,
  serialized_end=168,
  methods=[
  _descriptor.MethodDescriptor(
    name='speechRecognize',
    full_name='asr.speechRecognization.speechRecognize',
    index=0,
    containing_service=None,
    input_type=_ASRREQUEST,
    output_type=_ASRRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_SPEECHRECOGNIZATION)

DESCRIPTOR.services_by_name['speechRecognization'] = _SPEECHRECOGNIZATION

# @@protoc_insertion_point(module_scope)
